/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labrepo_leonardoborjas;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Leonardo Borjas
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popup = new javax.swing.JPopupMenu();
        Agregar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        raza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        M = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        altura = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        edad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        apodo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mara = new javax.swing.JTextField();
        musica = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        Agregar.setText("Agregar Hijo");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        popup.add(Agregar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popup.add(Eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        popup.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Adan");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbol);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Raza");

        jLabel4.setText("Genero");

        buttonGroup1.add(M);
        M.setSelected(true);
        M.setText("Masculino");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Femenino");

        jLabel5.setText("Altura");

        jLabel6.setText("Edad");

        jLabel7.setText("Fecha Nacimiento");

        jLabel8.setText("Apodo");

        apodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apodoActionPerformed(evt);
            }
        });

        jLabel9.setText("Mara");

        jLabel10.setText("Musica Favorita");

        jLabel11.setText("Descripcion");

        jLabel12.setText("Vida Sexual");

        jButton1.setText("Agregar Hijo al Arbol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BORRAR TODO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("About");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Guardar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jMenuItem2.setText("Cargar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Generar Reporte");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(raza)
                                    .addComponent(apellido)
                                    .addComponent(altura)
                                    .addComponent(edad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vida)))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(M)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(mara, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apodo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(musica)
                                    .addComponent(descripcion))))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(M)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(apodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(mara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        DateFormat df = new SimpleDateFormat("MM/dd/yy");
        String date = df.format(fecha.getDate());
        String name = nombre.getText();
        String lastname = apellido.getText();
        String nigga = raza.getText();
        int height = (Integer) altura.getValue();
        int age = (Integer) edad.getValue();
        String life = vida.getText();
        df.format(fecha.getDate());
        String nickname = apodo.getText();
        String gang = mara.getText();
        String music = musica.getText();
        String descript = descripcion.getText();
        String genero = "";
        if (M.isSelected()) {
            genero = "Masculino";
        } else {
            genero = "Femenino";
        }

        Hijo hijo = new Hijo(date, nickname, gang, music, descript,
                life, name, lastname, genero, nigga, height, age);

        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) m.getRoot();
        n.add(new DefaultMutableTreeNode(hijo));
        arbol.setModel(m);
        JOptionPane.showMessageDialog(this, "Hijo Agregado");
        fecha.setDate(null);
        nombre.setText("");
        apellido.setText("");
        raza.setText("");
        altura.setValue(0);
        edad.setValue(0);
        vida.setText("");
        apodo.setText("");
        mara.setText("");
        musica.setText("");
        descripcion.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_arbolMouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        Persona persona = (Persona) n.getUserObject();
        if (persona instanceof Padre) {
            String name = JOptionPane.showInputDialog("Nombre del hijo");
            String lastname = JOptionPane.showInputDialog("Apellido del hijo");
            String nigga = JOptionPane.showInputDialog("Raza del hijo");
            int height = Integer.parseInt(JOptionPane.showInputDialog("Altura del hijo"));
            int age = Integer.parseInt(JOptionPane.showInputDialog("Edad del hijo"));
            String life = JOptionPane.showInputDialog("Vida sexual del hijo");
            String nickname = JOptionPane.showInputDialog("Apodo del hijo");
            String gang = JOptionPane.showInputDialog("Mara del hijo");
            String music = JOptionPane.showInputDialog("Musica del hijo");
            String descript = JOptionPane.showInputDialog("Descrpcion");
            String genero = JOptionPane.showInputDialog("Genero del hijo");
            String date = JOptionPane.showInputDialog("Fecha de nacimiente mm/dd/yy");

            Hijo hijo = new Hijo(date, nickname, gang, music, descript,
                    life, name, lastname, genero, nigga, height, age);
            n.add(new DefaultMutableTreeNode(hijo));

        } else {
            String date = ((Hijo) persona).getFechanacimiento();
            String name = persona.getNombre();
            String lastname = persona.getApellido();
            String nigga = persona.getRaza();
            int height = persona.getAltura();
            int age = persona.getEdad();
            String life = ((Hijo) persona).getVidasexual();
            String nickname = ((Hijo) persona).getApodo();
            String gang = ((Hijo) persona).getMara();
            String music = ((Hijo) persona).getMusica();
            String descript = ((Hijo) persona).getDescripcion();
            String genero = persona.getGenero();

            String trabajo = JOptionPane.showInputDialog("Cual es su nuevo trabajo");
            String clasesocial = JOptionPane.showInputDialog("Cual clase social esta usted ahora");
            String iq = JOptionPane.showInputDialog("Cual es su iq?");
            String carrera = JOptionPane.showInputDialog("Cual carrera estudio?");
            String estado = JOptionPane.showInputDialog("Cual es su estado mental?");
            String esposa = JOptionPane.showInputDialog("Cual es su esposa?");
            Padre padre = new Padre(trabajo, clasesocial, iq, carrera,
                    estado, esposa, date, nickname, gang, music, descript, life, name,
                    lastname, genero, nigga, height, age);

            n.setUserObject(padre);

            name = JOptionPane.showInputDialog("Nombre del hijo");
            lastname = JOptionPane.showInputDialog("Apellido del hijo");
            nigga = JOptionPane.showInputDialog("Raza del hijo");
            height = Integer.parseInt(JOptionPane.showInputDialog("Altura del hijo"));
            age = Integer.parseInt(JOptionPane.showInputDialog("Edad del hijo"));
            life = JOptionPane.showInputDialog("Vida sexual del hijo");
            nickname = JOptionPane.showInputDialog("Apodo del hijo");
            gang = JOptionPane.showInputDialog("Mara del hijo");
            music = JOptionPane.showInputDialog("Musica del hijo");
            descript = JOptionPane.showInputDialog("Descrpcion");
            genero = JOptionPane.showInputDialog("Genero del hijo");
            date = JOptionPane.showInputDialog("Fecha de nacimiente mm/dd/yy");

            Hijo hijo = new Hijo(date, nickname, gang, music, descript,
                    life, name, lastname, genero, nigga, height, age);
            n.add(new DefaultMutableTreeNode(hijo));
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        Persona persona = (Persona) n.getUserObject();
        if (persona instanceof Hijo) {
            String name = JOptionPane.showInputDialog("Modificar nombre");
            String lastname = JOptionPane.showInputDialog("Modificar apellido ");
            String nigga = JOptionPane.showInputDialog("Modificar raza");
            int height = Integer.parseInt(JOptionPane.showInputDialog("Modificar altura"));
            int age = Integer.parseInt(JOptionPane.showInputDialog("Modificar edad"));
            String life = JOptionPane.showInputDialog("Modificar vida sexual");
            String nickname = JOptionPane.showInputDialog("Modificar apodo");
            String gang = JOptionPane.showInputDialog("Modificar mara ");
            String music = JOptionPane.showInputDialog("Modificar musica favorita");
            String descript = JOptionPane.showInputDialog("modificar descripcion ");
            String genero = JOptionPane.showInputDialog("modificar genero");
            String date = JOptionPane.showInputDialog("modificar fecha");

            ((Hijo) persona).setNombre(name);
            ((Hijo) persona).setApellido(lastname);
            ((Hijo) persona).setRaza(nigga);
            ((Hijo) persona).setAltura(height);
            ((Hijo) persona).setEdad(age);
            ((Hijo) persona).setVidasexual(life);
            ((Hijo) persona).setApodo(nickname);
            ((Hijo) persona).setMara(gang);
            ((Hijo) persona).setMusica(music);
            ((Hijo) persona).setDescripcion(descript);
            ((Hijo) persona).setGenero(genero);
            ((Hijo) persona).setFechanacimiento(date);

        } else {
            String name = JOptionPane.showInputDialog("Modificar nombre");
            String lastname = JOptionPane.showInputDialog("Modificar apellido ");
            String nigga = JOptionPane.showInputDialog("Modificar raza");
            int height = Integer.parseInt(JOptionPane.showInputDialog("Modificar altura"));
            int age = Integer.parseInt(JOptionPane.showInputDialog("Modificar edad"));
            String life = JOptionPane.showInputDialog("Modificar vida sexual");
            String nickname = JOptionPane.showInputDialog("Modificar apodo");
            String gang = JOptionPane.showInputDialog("Modificar mara ");
            String music = JOptionPane.showInputDialog("Modificar musica favorita");
            String descript = JOptionPane.showInputDialog("modificar descripcion ");
            String genero = JOptionPane.showInputDialog("modificar genero");
            String date = JOptionPane.showInputDialog("modificar fecha");
            String trabajo = JOptionPane.showInputDialog("modificar trabajo");
            String clasesocial = JOptionPane.showInputDialog("modificar Clase Social");
            String iq = JOptionPane.showInputDialog("modificar IQ");
            String carrera = JOptionPane.showInputDialog("modificar Carrera");
            String estado = JOptionPane.showInputDialog("modificar estado");
            String esposa = JOptionPane.showInputDialog("modificar esposa");

            ((Padre) persona).setNombre(name);
            ((Padre) persona).setApellido(lastname);
            ((Padre) persona).setRaza(nigga);
            ((Padre) persona).setAltura(height);
            ((Padre) persona).setEdad(age);
            ((Padre) persona).setVidasexual(life);
            ((Padre) persona).setApodo(nickname);
            ((Padre) persona).setMara(gang);
            ((Padre) persona).setMusica(music);
            ((Padre) persona).setDescripcion(descript);
            ((Padre) persona).setGenero(genero);
            ((Padre) persona).setFechanacimiento(date);
            ((Padre) persona).setTrabajo(trabajo);
            ((Padre) persona).setClasesocial(clasesocial);
            ((Padre) persona).setIq(iq);
            ((Padre) persona).setCarrera(carrera);
            ((Padre) persona).setEstado(estado);
            ((Padre) persona).setEsposa(esposa);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        m.removeNodeFromParent(n);
        arbol.setModel(m);
    }//GEN-LAST:event_EliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        arbol.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("Adan")));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This work was done by Leonardo Borjas on a\n"
                + "lab he had to recover because of a trip.\n"
                + "This Work is also part of Sota Property\n"
                + "Version: 50+45");
        
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(this);
        File archivo=jfc.getSelectedFile();
        DefaultTreeModel m=(DefaultTreeModel)arbol.getModel();
        Escribir es=new Escribir(m,archivo);
        try {
            es.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(this);
        File archivo=jfc.getSelectedFile();
        try {
            DefaultTreeModel temp;
            if (archivo.exists()) {
                FileInputStream entrada = new FileInputStream(archivo);
                ObjectInputStream objeto = new ObjectInputStream(entrada);
                DefaultTreeModel m=(DefaultTreeModel)objeto.readObject();
                arbol.setModel(m);
                objeto.close();
                entrada.close();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void escribir() throws IOException{
        File archivo=new File("./Reporte.txt");
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(archivo, false);
            bw = new BufferedWriter(fw);
            DefaultTreeModel m = (DefaultTreeModel)arbol.getModel();
            DefaultMutableTreeNode n=(DefaultMutableTreeNode)m.getRoot();
            for (int i = 0; i < n.getChildCount(); i++) {
                bw.write(n.getChildAt(i).toString()+";");
            }
            bw.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
        bw.close();
        fw.close();
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
            escribir();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JRadioButton M;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JSpinner altura;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apodo;
    private javax.swing.JTree arbol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField descripcion;
    private javax.swing.JSpinner edad;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mara;
    private javax.swing.JTextField musica;
    private javax.swing.JTextField nombre;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JTextField raza;
    private javax.swing.JTextField vida;
    // End of variables declaration//GEN-END:variables

}
